### ISSUE TITLE
사이트 접속 오류 Fix

### ISSUE THREAD

**Issue by HyungJu** [Juneyoung-Kang/school-meal#1]
1. simple_html_dom.php 필요하지 않습니다.
DomDocument 객체는 PHP Dom 확장을 설치해야 사용할수 있습니다.

[https://hyungjus.com/meal](link) 에 작동 파일을 올려두었으니 확인바랍니다.
htaccess는 무의미한것 같아 적용하지 않았습니다

**Comment by Juneyoung-Kang** [comment]
확인했습니다. 

현재 호스팅 이전 작업으로 접속이 원활하지 않습니다ㅠㅠ
